### ISSUE TITLE
database migration error

### ISSUE THREAD

**Issue by Sen-Zhang** [tsurupin/portfolio#71]
Got an error when running db:migrate

``` ruby
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long;
 max key length is 767 bytes: CREATE  INDEX `index_items_on_target_type_and_target_id` 
USING btree ON `items` (`target_type`, `target_id`)
```
## MySQL Version

5.6.20-debug

**Comment by tsurupin** [comment]
@Sen-Zhang Thanks! I'll look into the error soon.

**Comment by Sen-Zhang** [comment]
@tsurupin It works fine when I switched to `utf8` from `utf8mb4`. May I have an answer to why choosing `utf8mb4` over `utf8`?

**Comment by tsurupin** [comment]
@Sen-Zhang 
Thank you for checking. 
The reason I chose utf8mb4 is because utf8 cannot  handle some emojis.

**Comment by Sen-Zhang** [comment]
@tsurupin I see
